Add MvNormalMeanScalePrecision distribution
ReactiveBayes/ExponentialFamily.jl pull request #206
Opened 2024-08-21 10:14 UTC by albertpod

This PR was initially aimed at addressing https://github.com/ReactiveBayes/ReactiveMP.jl/issues/387, which it still does. The distribution in question is parametrized by the mean and scale parameter of the precision matrix. 

Initially, I implemented it as part of the `MultivariateNormalDistributionsFamily`. However, the conversions between `MvNormalMeanScalePrecision` and other distributions in this "class" don't always hold.

During the process, @Nimrais suggested that this distribution could be particularly interesting for `ExponentialFamilyProjections.jl`. To make it more useful, we need to optimize methods related to the computation of the Fisher information matrix. I made a first attempt to improve performance by modifying the computation of `kron(invη2, invη2)`. I believe further improvements are possible, but this serves as a starting point.

Any suggestions for additional optimizations to enhance the distribution's effectiveness are much welcome.

**UPD**: I added the piece of code that actually fixes the https://github.com/ReactiveBayes/ReactiveMP.jl/issues/387

2024-09-02 15:02 UTC, albertpod commented
ping @Nimrais

2024-09-16 14:55 UTC, Nimrais requested changes
First, great work on implementing the MvNormalMeanScalePrecision distribution and integrating it into the ExponentialFamily.jl.

2024-09-16 14:55 UTC, Nimrais commented on src/distributions/normal_family/mv_normal_mean_scale_precision.jl
> +function BayesBase.rand(rng::AbstractRNG, dist::MvGaussianMeanScalePrecision{T}) where {T}
function BayesBase.rand(rng::AbstractRNG, dist::MvGaussianMeanScalePrecision{T}) where {T}
    μ, γ = mean(dist), scale(dist)
    return μ .+ (1 / γ) .* randn(rng, T, length(μ))
end

Avoid constructing the identity matrix I(length(μ)) and directly scale the random vector.
Use broadcasting with ., which is more efficient and avoids unnecessary allocations.

2024-09-16 14:55 UTC, Nimrais commented on src/distributions/normal_family/mv_normal_mean_scale_precision.jl
> +function BayesBase.rand!(
Similiarly to rand

```
function BayesBase.rand!(rng::AbstractRNG, dist::MvGaussianMeanScalePrecision, container::AbstractArray{T}) where {T <: Real}
    μ, γ = mean(dist), scale(dist)
    randn!(rng, container)
    @. container = μ + (1 / γ) * container
    return container
end
```

Btw I think rand just need to re-use rand!

2024-09-16 14:55 UTC, Nimrais commented on src/distributions/normal_family/mv_normal_mean_scale_precision.jl
> +function Distributions.sqmahal!(r, dist::MvNormalMeanScalePrecision, x::AbstractVector)
```
function Distributions.sqmahal!(r, dist::MvNormalMeanScalePrecision, x::AbstractVector)
    μ = dist.μ
    γ = dist.γ
    @inbounds @simd for i in eachindex(r)
        r[i] = μ[i] - x[i]
    end
    return γ * dot(r, r)
end
```
Replace dot3arg(r, invcov(dist), r) with γ * dot(r, r), since invcov(dist) = γ * I.
Eliminates the need to compute or store invcov(dist).

2024-09-16 14:55 UTC, Nimrais commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +            getfisherinformation(NaturalParametersSpace(), MvNormalMeanScalePrecision)(η) ≈
Why do we have an equality here?

MvNormalMeanScalePrecision has n+1 parameters, so the fisher is (n+1, n+1) for MvNormalMeanCovariance it would be (n+n^2, n+n^2).

2024-09-25 14:43 UTC, albertpod commented
Thanks for refactoring this, @Nimrais!

2024-09-26 06:42 UTC, bvdmitri commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
I think here is supposed to be `cholinv`?

2024-09-26 06:42 UTC, bvdmitri commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
```suggestion
        cholinv_alloc_small = @allocated cholinv(ef_small)
```

2024-09-26 06:42 UTC, bvdmitri commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
All tests that are failing involve the `cholinv_time_small` so it might be the reason for those failures

2024-09-26 06:47 UTC, bvdmitri commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
Maybe we have a fast algorithm to compute the `Cholesky` factorization for this kind of matrices? It looks like a rank-1 update `D + u'u` so perhaps `Cholesky` can be done super fast? and then the `inv` of it too. If this is the case we could add this type of a matrix in `BayesBase` for example and write a specialized method for `fastcholesky` in `FastCholsky.jl`

2024-09-26 07:46 UTC, Nimrais commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
Yes, you have a right idea I suppose. Yesterday evening I asked a question in the Julia slack about this matrix. And Woodbury matrix identity was suggested to me. I found that it's a diagonal with a 2-rank update.

```julia
A = zeros(k+1, k+1)
A[1:k, 1:k] .= -inv(2*η2) * I(k)
A[k+1, k+1] = η2_part
U = zeros(k+1)
V = zeros(k+1)

U[k+1] = 1
V[1:k] = η1 * inv(2*η2^2)
V[k+1] = 0

M = A + U * V' + V * U'
```

Applying Woodbury identity

```julia
A_inv = zeros(k+1, k+1)
A_inv[1:k, 1:k] .= -2*η2 * I(k)
A_inv[k+1, k+1] = inv(A[k+1, k+1])

# Construct U and V
U = zeros(k+1, 2)
V = zeros(k+1, 2)

U[k+1, 1] = 1
U[1:k, 2] = η1 * inv(2*η2^2)


# Construct C and compute its inverse
C = [0 1; 1 0]
C_inv = inv(C)

S = C_inv + U' * A_inv * U

# Compute S_inv
S_inv = inv(S)

# Compute M_inv using the Woodbury identity
fisher_inv = A_inv - A_inv * U * S_inv * U' * A_inv
```

2024-09-26 07:49 UTC, Nimrais commented on test/distributions/normal_family/mv_normal_mean_scale_precision_tests.jl
> +        cholinv_alloc_small = @allocated fisherinformation(ef_small)
This package was suggested to me to use once I have decomposition https://github.com/JuliaLinearAlgebra/WoodburyMatrices.jl. However I am not sure.

2024-10-15 08:48 UTC, bvdmitri commented
@Nimrais ping, what needs to be done to finish this PR?

2024-10-15 09:51 UTC, Nimrais commented
@bvdmitri The basic functionality is now implemented. The only remaining task is to implement the multiplication of the Fisher matrix with another matrix for the Arrowhead matrix structure in BayesBase. Currently, this multiplication is only done in our tests. There's already a generic method for all matrix structures using the getindex method, so implementing this specific case is the last thing we need to do.

2024-10-15 11:31 UTC, Nimrais commented
@bvdmitri basically we need this PR https://github.com/ReactiveBayes/BayesBase.jl/pull/25 be merged to finish this one

2024-10-22 11:13 UTC, Nimrais reviewed
Try to withdraw from reviewing

2024-10-22 14:50 UTC, wouterwln reviewed
I think you should review your BayesBase dependency. Other than that, the PR looks good to me and I think we can merge.

2024-10-22 14:50 UTC, wouterwln commented on Project.toml
> +BayesBase = "1.5.0"
Is there stuff in `BayesBase` 1.5.0 that you need specifically?

2024-10-22 14:51 UTC, Nimrais commented on Project.toml
> +BayesBase = "1.5.0"
yes, the arrowheadmatrix and the all methods for it to make the CI pass

2024-10-22 14:52 UTC, Nimrais commented on Project.toml
> +BayesBase = "1.5.0"
https://github.com/ReactiveBayes/BayesBase.jl/compare/v1.4.0...v1.5.0

2024-10-22 14:54 UTC, Nimrais approved these changes

2024-10-22 17:18 UTC, bvdmitri approved these changes
Great work gentlemens

2024-10-23 08:31 UTC, merged