Dirichlet tensor
ReactiveBayes/ExponentialFamily.jl pull request #219
Opened 2024-12-24 17:41 UTC by Raphael-Tresor

#Issue
The branch is not ExponentialFamily compatible yet. The pack unpack mechanism does not work.

2024-12-26 10:48 UTC, bvdmitri commented on src/distributions/tensor_dirichlet.jl
> +    TensorDirichlet{T <: Real, A <: AbstractArrray{T,3}} <: ContinuousTensorDistribution
Do not document the `{  }` thing since its an internal detail and its also wrongly documented

2024-12-26 10:49 UTC, bvdmitri commented on src/distributions/tensor_dirichlet.jl
> +        out =+ logpdf(Dirichlet(dist.a[:,i]), @view x[:,i])
Did you mean to write `+=`?

2024-12-26 10:50 UTC, bvdmitri commented on src/distributions/tensor_dirichlet.jl
> +    out = 0
```suggestion
    out = zero(eltype(x))
```

2024-12-26 10:52 UTC, bvdmitri commented on test/distributions/tensor_dirichlet_test.jl
> +    @test var(TensorDirichlet(tensorDiri)) == varDiri
Thats quite a strange interface for `var`

2024-12-26 10:52 UTC, bvdmitri commented on test/distributions/tensor_dirichlet_test.jl
> +@test_broken "TensorDirichlet: ExponentialFamilyDistribution" begin
do not write tests outside of `@testitem`

2024-12-26 10:53 UTC, bvdmitri commented on test/distributions/tensor_dirichlet_test.jl
> +@test_broken "TensorDirichlet: prod with ExponentialFamilyDistribution" begin
do not write tests outside of `@testitem`

2024-12-26 10:58 UTC, bvdmitri requested changes
I'm quite skeptical about this PR. First of all, is this distribution is from exponential family? If not, why should it belong to this package? 

Second, why to do all these shenanigans with `a[:, m, n]` when you could simply to an array of `Dirichlet` distributions? 

E.g. 
```
a = [
    Dirichlet([ 0.1, 0.9 ]), Dirichlet([ 0.1, 0.9 ]),
    Dirichlet([ 0.1, 0.9 ]), Dirichlet([ 0.1, 0.9 ])
]
```
and then later on simply
```
a[1, 2] # returns Dirichlet 
```

I'm also not sure if the functionality is really correct, the `logpdf` can't be correct right? Why tests didn't pick it up?

2025-01-07 10:38 UTC, Raphael-Tresor commented on src/distributions/tensor_dirichlet.jl
> +        out =+ logpdf(Dirichlet(dist.a[:,i]), @view x[:,i])
yes indeed

2025-01-07 10:44 UTC, Raphael-Tresor commented
> I'm quite skeptical about this PR. First of all, is this distribution is from exponential family? If not, why should it belong to this package?
> 
> Second, why to do all these shenanigans with `a[:, m, n]` when you could simply to an array of `Dirichlet` distributions?
> 
> E.g.
> 
> ```
> a = [
>     Dirichlet([ 0.1, 0.9 ]), Dirichlet([ 0.1, 0.9 ]),
>     Dirichlet([ 0.1, 0.9 ]), Dirichlet([ 0.1, 0.9 ])
> ]
> ```
> 
> and then later on simply
> 
> ```
> a[1, 2] # returns Dirichlet 
> ```
> 
> I'm also not sure if the functionality is really correct, the `logpdf` can't be correct right? Why tests didn't pick it up?

I discussed this with @Nimrais, and I think it is indeed a member of the exponential family. 
About the implementation:  creating an array of Dirichlets was my first idea, but after a discussion with @wouterwln I changed my mind. It seems that an array of Dirichlets might be slow and working directly with Float-array should be more efficient. I will think about it again.

2025-01-07 12:07 UTC, bvdmitri commented
@Raphael-Tresor 

> It seems that an array of Dirichlets might be slow and working directly with Float-array should be more efficient. I will think about it again.

I agree that working directly with Float-array, but only if you implement it correctly. I doubt that the current implementation is faster or more efficient because it creates a lot of slices and allocates *new* memory on every access, which is perhaps even slower than using arrays of Dirichlet distributions. You sometimes use `@view` but not everywhere. I don't have any benchmarks, it just more like a feeling. This being said, I don't really have a strong opinion on how to implement it and leave the choice to you.

2025-01-07 12:11 UTC, wouterwln commented
I'll work on performance, for now we just need a correct generalization of `MatrixDirichlet` for higher order tensors, such that we can parameterize `Transition` and `TransitionMixture` nodes.

2025-01-07 12:24 UTC, Nimrais commented
>@bvdmitri I'll work on performance, for now we just need a correct generalization of MatrixDirichlet for higher order tensors, such that we can parameterize Transition and TransitionMixture nodes.

If the performance is not a goal, why not make an array of Dirichlet distributions? It's far easier to understand at least.

2025-01-07 12:32 UTC, Nimrais requested changes

2025-01-07 12:32 UTC, Nimrais commented on src/distributions/tensor_dirichlet.jl
> +    ## The element of the array should be the a categorical distribution (an vector of postive value that sum to 1)
It's not a comment, this is the documentation make it a docstring, smt like this
```
"""
BayesBase.insupport(ef::ExponentialFamilyDistribution{TensorDirichlet}, x)

Check if the input `x` is within the support of a Tensor Dirichlet distribution.

Requirements:
- Each column of x must represent a valid categorical distribution (sum to 1, all values ≥ 0)
- Dimensions must match the natural parameters of the distribution

"""
```

2025-01-07 12:32 UTC, Nimrais commented on src/distributions/tensor_dirichlet.jl
> +function BayesBase.vague(::Type{<:TensorDirichlet}, dims::Int)
In one of the methods, you specify the type of ones, while in another, you don't. Is there any reason why you aren't writing it like this?

```
function BayesBase.vague(::Type{<:TensorDirichlet}, dims::Int) 
    return TensorDirichlet(ones(Float64, dims, dims))
end
```

2025-01-07 12:32 UTC, Nimrais commented on src/distributions/tensor_dirichlet.jl
> +extract_collection(dist::TensorDirichlet) = [dist.a[:,i] for i in CartesianIndices(Base.tail(size(dist.a)))]
`extract_collection(dist::TensorDirichlet) = (view(dist.a, :, i) for i in CartesianIndices(Base.tail(size(dist.a))))`?

2025-01-07 12:34 UTC, wouterwln commented
@Nimrais Because in the end we do need a performant implementation of this, which would require the data to be stored the way Raphael coded it. It is a lot easier to implement performant versions of methods if the underlying data structure does not change anymore.

2025-01-07 12:50 UTC, Nimrais commented
> Because in the end we do need a performant implementation of this, which would require the data to be stored the way Raphael coded it. It is a lot easier to implement performant versions of methods if the underlying data structure does not change anymore.

Sure, but then it would be nice to see the proof that it works faster. 

For example, a test that shows that the current way of implementing things is better than the naïve. Because if, at some point in time, it is starting to become slower, what is the point?

For example, smt like this, but written carefully 

```
using ExponentialFamily
using BenchmarkTools
using Random
using Distributions
using Test

struct ArrayDirichlet{T}
    distributions::Array{Dirichlet{T}, 2}
end

function array_dirichlet(params::Array{T, 3}) where T
    m, n, k = size(params)
    dists = Array{Dirichlet{T}, 2}(undef, n, k)
    for i in 1:n, j in 1:k
        dists[i,j] = Dirichlet(params[:,i,j])
    end
    return ArrayDirichlet(dists)
end

struct TensorDirichlet{T}
    a::Array{T, 3}
end

dim = 10
grid_size = 20 
params = rand(dim, grid_size, grid_size) .+ 0.1

tensor_impl = TensorDirichlet(params)
array_impl = array_dirichlet(params)

test_points = [rand(dim, grid_size, grid_size) for _ in 1:100]
for x in test_points
    x ./= sum(x, dims=1)
end

tensor_bench = @benchmark for x in $test_points
    for i in 1:grid_size, j in 1:grid_size
        logpdf(Dirichlet(view($tensor_impl.a,:,i,j)), view(x,:,i,j))
    end
end

array_bench = @benchmark for x in $test_points
    for i in 1:grid_size, j in 1:grid_size
        logpdf($array_impl.distributions[i,j], view(x,:,i,j))
    end
end

println("Tensor Implementation:")
println("---------------------")
show(stdout, MIME("text/plain"), tensor_bench)
println("\n\nArray Implementation:")
println("--------------------")
show(stdout, MIME("text/plain"), array_bench)
@test min(array_bench.times...) < min(tensor_bench.times...)
```

2025-01-08 13:25 UTC, wouterwln commented
@Raphael-Tresor, can you add tests for `mean`, `cov`, `std`, and basic methods like that in the same way in which I implemented the tests for `logpdf`? So you generate the "correct" answer using the existing `Dirichlet` implementation and check our implementation?

2025-01-08 13:40 UTC, wouterwln requested changes
I'd like to see tests for the following functions:

- [ ] `params` (especially with `MeanParameterSpace`
- [ ] `getbasemeasure`
- [ ] `entropy`
- [ ] `mean`
- [x] `var`
- [ ] `prod`
- [x] `cov`
- [ ] `std`

These should be easily tested with `Dirichlet` from `Distributions.jl`

2025-01-08 13:43 UTC, Raphael-Tresor commented
> @Raphael-Tresor, can you add tests for `mean`, `cov`, `std`, `prod` and basic methods like that in the same way in which I implemented the tests for `logpdf`? So you generate the "correct" answer using the existing `Dirichlet` implementation and check our implementation?

I will do it tomorrow afternoon 9/01.

2025-01-10 11:43 UTC, Nimrais commented
I am currently working on the PR. It is not ready for review, so I will convert it to a draft.

2025-01-14 12:06 UTC, wouterwln approved these changes
I think we're ready to merge. There is still some minor stuff I will work on but everything considered I think we're ready to merge.

2025-01-14 12:06 UTC, wouterwln commented on src/distributions/tensor_dirichlet.jl
> +    return map(x -> pdf(dist, x), xs)
Do we really need this function @Nimrais ? Because I can spot a bug as it is right now. Either we delete this function or I can patch the bug. Let me know.

2025-01-14 12:12 UTC, Nimrais commented on src/distributions/tensor_dirichlet.jl
> +    return map(x -> pdf(dist, x), xs)
Since the implemented `rand(Td, n)` returns a vector of samples, I don't think it's easy to fix. To be compatible with both Distributions.jl and ExponentialFamily.jl, the distribution needs to implement a method that will evaluate a collection of samples.

So the short answer is yes, we need it. 

The long answer is that the bug is not only here but also in the rand method because the rand method doesn't work according to the Distributions.jl API.

2025-01-14 12:15 UTC, Nimrais commented
> by the way @Nimrais @bvdmitri This completely replaces MatrixDirichlet. We should probably remove it. What do you think? Strictly speaking because we break some existing functionality we should then release a new major version of the package.

We can do it in a separate PR. We can have it anyway but re-use code here to implement it. Also, MatrixDirechlet could be slightly more performant in some edge cases.

2025-01-14 12:24 UTC, Nimrais approved these changes

2025-01-15 10:41 UTC, merged